# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
argument_specs:
  main:
    short_description:
      Ensure that a host on a storage system exists and has host WWPNs.
    description:
      - Ensure that a host on a storage system exists and has host WWPNs.
      - This role is idempotent.
    author:
      - Andreas Maier
    options:
      in_params:
        type: dict
        required: true
        description: Input parameters for the role.
        options:
          log_file:
            type: str
            required: false
            description: Path name of log file.
          sar_type:
            type: str
            required: true
            description: Type of the storage system.
            choices:
              - ds8k
              - fs9k
          sar_hostname:
            type: str
            required: true
            description: IP address or hostname of the storage system for
              logging in.
          sar_username:
            type: str
            required: true
            description: Username on the storage system.
          sar_password:
            type: str
            required: true
            description: Password on the storage system.
          host_name:
            type: str
            required: true
            description: Name of the host to be created.
          host_wwpns:
            type: list
            elements: str
            required: true
            description: WWPNs for the host, in C(hh:hh...) or C(hhhh...) format.
      out_params:
        type: dict
        required: false
        description:
          - Output parameters for the role.
          - Their values are the names of variables to be set upon return from
            the role.
        options:
          host_info:
            type: str
            required: false
            description:
              - Properties of the host (specific to C(sar_type)).
              - "Type: dict"
