# pyproject.toml file for ansible-doc-template-extractor
# Documentation:
# pyproject.toml: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
# setuptools items: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html

[build-system]
requires = [
    # Keep in sync with requirements-base.txt
    "setuptools>=70.0.0",
    "setuptools-scm[toml]>=9.2.0",
    "wheel>=0.41.3"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
platforms = ["any"]
script-files = []
zip-safe = true
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
# setuptools needs all sub-packages to be specified as well to avoid the
# ambiguity warning. That can be done by specifyng 'packages' with a full list
# of packages including sub-packages, or by specifying 'packages.find' with
# wildcards. The strings in 'packages.find' are matched using glob pattern
# matching against the package path.
where = ["src"]
include = [
    "ansible_doc_template_extractor",
    "ansible_doc_template_extractor.*",
]

[project.scripts]
ansible-doc-template-extractor = "ansible_doc_template_extractor.ansible_doc_template_extractor:main"

[project]
name = "ansible-doc-template-extractor"
description = "Ansible Documentation Template Extractor"
authors = [
    {name = "Andreas Maier", email = "andreas.r.maier@gmx.de"}
]
maintainers = [
    {name = "Andreas Maier", email = "andreas.r.maier@gmx.de"}
]

readme = "README.md"
license = {text = "Apache License, Version 2.0"}
keywords = ["ansible", "documentation", "template"]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Information Technology",
    'Intended Audience :: System Administrators',
    "Topic :: System :: Systems Administration",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
requires-python = ">=3.8"
dynamic = ["version", "dependencies"]

[project.urls]
Homepage = "https://github.com/andy-maier/ansible-doc-template-extractor"
"Bug Tracker" = "https://github.com/andy-maier/ansible-doc-template-extractor/issues"
"Source Code" = "https://github.com/andy-maier/ansible-doc-template-extractor"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools_scm]
# Get the version from the Git tag, and write a version file:
version_file = "src/ansible_doc_template_extractor/_version_scm.py"
