$schema: "http://json-schema.org/draft/2020-12/schema"
description: Playbook input variable 'params'.
type: object
additionalProperties: false
required:
  - server
  - version
properties:
  server:
    description: IP address or hostname of the server that runs the XYZ container.
    type: string
  version:
    description: Desired new version of the XYZ container.
    type: string
  foo_object:
    description: Demonstrate an object
    type: object
    additionalProperties: false
    required:
      - bar
      - bar_object
    properties:
      bar:
        description: A string property in foo_object
        type: string
      bar_object:
        description: A nested object in foo_object
        type: object
        additionalProperties: false
        required:
          - cat
        properties:
          cat:
            description: A string property in the nested bar_object
            type: string
  foo_array:
    description: Demonstrate an array of objects
    type: array
    items:
      description: Nested array item
      type: object
      additionalProperties: false
      required:
        - bar
        - bar_object
      properties:
        bar:
          description: A string property in the array item
          type: string
        bar_object:
          description: A nested object in the array item
          type: object
          additionalProperties: false
          required:
            - cat
          properties:
            cat:
              description: A string property in the nested bar_object
              type: string
