$schema: "http://json-schema.org/draft/2020-12/schema"
title: JSON schema for output parameters of xyz_upgrade_schema_file playbook
description: Output parameters of xyz_upgrade_schema_file playbook
type: object
additionalProperties: true  # Ansible passes several input variables
required:
  - output
properties:
  output:
    description: Object with output parameters
    type: object
    additionalProperties: false
    required:
      - previous_version
    properties:
      previous_version:
        description: Version of the XYZ container before the upgrade.
        type: string
